### PR TITLE
Formation - Update index.md

### PR DESCRIPTION
**Pull request by jhickner**
Add documentation for `metadata` field.

### CODE REVIEW

**Comment by jhickner** [comment]
@cla-bot check

**Review by tjannan — APPROVED** [review]

**Comment by tjannan** [comment]
@dbmiller1128 could you please take a look at this?

**Comment by dbmiller1128** [comment]
@tjannan @jhickner - a few questions about the new `metadata` event attribute:

1. What events will the new event attribute `metadata`  be received with?  
2. What type of data will be included in the JSON - can you share an example?   JSON is not a supported data type, so the data will be treated as string, and there is a 4096 limit, which may be truncated.
3. How will this field be used in mParticle?

cc @jakeaustin

**Comment by jhickner** [comment]
@dbmiller1128 
1. All events
2. The received data will be key-value pairs, representing additional client-specific metadata that the client requests to be added to each offer. Initially we have a request to add a field called `campaign_id`. Example: ```"metadata":"{\"campaign_id\":\"<customer_id>\"}"```
3. The client will extract these fields and use them to tailor the offer presentation

**Comment by jakeaustin** [comment]
Hey @jhickner - thank you for the added context here.

Since JSON is not a supported type in mP, clients will not be able to extract these fields in our platform. They might be able to forward the stringified JSON to another system that can parse it, but that will depend on the destination platform.

For these attributes, the best approach may be to have every additional field represented as its own custom event attribute (see [here](https://docs.mparticle.com/developers/server/json-reference/#common-event-data-node-properties)). Would Formation be able to parse the metadata in this manner before forwarding to the mParticle Events API?

**Comment by tjannan** [comment]
Hi @jakeaustin - it's not really feasible for us to parse it all out into distinct fields, as these metadata fields have some variability on a per-customer basis. There's no expectation that a customer would need to extract the fields within mParticle (though if that became the case for a field consistently passed through, we would promote it) but instead metadata is meant to be consumed downstream from mParticle with decisioning made on other fields (typically game_type).

**Comment by dbmiller1128** [comment]
https://docs.mparticle.com/integrations/formation/feed/ updated - closing PR

**Pull request closed without merging**
